// Cabecalhos extraidos do modelo VRS local inclusao_modelo.xlsx.
// SHA-256: a758b9032c94fc3dfc2c9560d3325c55ec9101d2b03c8de71a5149e743d5d813
// O XLSX real usa colunas contiguas; o TXT acompanhante tem lacunas.
export const VRS_XLSX_COLUNAS = {
  "HEADER": [
    "tipo",
    "termo",
    "codigo_carteira",
    "cpf_cnpj_cedente",
    "coobrigacao"
  ],
  "ATIVO": [
    "chave_unica_do_ativo",
    "cnpj_do_originador",
    "cpf_cnpj_do_emissor",
    "cpf_cnpj_do_devedor",
    "nome_devedor",
    "cep_do_devedor",
    "endereco_do_devedor",
    "numero_do_devedor",
    "complemento_do_devedor",
    "bairro_do_devedor",
    "municipio_do_devedor",
    "uf_do_devedor",
    "email_devedor",
    "telefone_devedor",
    "tipo_do_ativo",
    "tipo_preco",
    "metodo_de_preco",
    "valor_de_emissao",
    "valor_de_compra",
    "valor_de_vencimento",
    "data_de_emissao",
    "data_de_inicio_vigencia",
    "data_vencimento",
    "data_de_vencimento_original",
    "spread_da_emissao",
    "percentual_do_indice_de_referencia",
    "numero_da_emissao_do_ativo",
    "quantidade_de_unidades_emitidas",
    "valor_de_provisao",
    "taxa_de_juros_operacao",
    "modalidade_operacao",
    "quantidade_original_parcelas",
    "valor_liquido_credito",
    "valor_total_credito",
    "nome_registradora",
    "campo_customizado1",
    "campo_customizado2",
    "campo_customizado3",
    "campo_customizado4",
    "campo_customizado5"
  ],
  "FLUXO": [
    "chave_unica_ativo",
    "chave_unica_parcela",
    "cpf_cnpj_emissor_bancarizador",
    "data_vencimento_parcela",
    "data_vencimento_original_parcela",
    "data_pagamento",
    "tipo_evento",
    "taxa_evento",
    "valor_no_vencimento",
    "campo_customizado1",
    "campo_customizado2",
    "campo_customizado3",
    "campo_customizado4",
    "campo_customizado5"
  ],
  "PAGAMENTO": [
    "codigo_banco",
    "codigo_agencia",
    "numero_conta",
    "digito_verificador_conta",
    "cpf_cnpj_favorecido",
    "nome_do_favorecido",
    "valor_da_transacao"
  ]
} as const
