// Closed vocabulary: never log provider bodies, fiscal fields, secrets or arbitrary error messages.
const failureCodes = [
  'OPENAI_NF_FALLBACK_DISABLED', 'OPENAI_NF_NOT_CONFIGURED', 'OPENAI_NF_FILE_SIZE_INVALID',
  'OPENAI_NF_AUTH_FAILED', 'OPENAI_NF_TEMPORARILY_UNAVAILABLE', 'OPENAI_NF_REQUEST_FAILED',
  'OPENAI_NF_REQUEST_INVALID', 'OPENAI_NF_TIMEOUT', 'OPENAI_NF_EMPTY_RESPONSE',
  'OPENAI_NF_INVALID_RESPONSE', 'OPENAI_NF_RESPONSE_INCOMPLETE', 'OPENAI_NF_OUTPUT_LIMIT',
  'OPENAI_NF_RESPONSE_REFUSED', 'OPENAI_NF_DOCUMENT_UNCERTAIN', 'OPENAI_NF_LOW_CONFIDENCE',
  'OPENAI_NF_ACCESS_KEY_INVALID', 'OPENAI_NF_MULTIPLE_ACCESS_KEYS', 'OPENAI_NF_DATE_KEY_CONFLICT',
  'OPENAI_NF_ISSUE_DATE_MISSING', 'OPENAI_NF_TOTAL_MISSING', 'OPENAI_NF_NO_RELIABLE_FIELDS',
  'OPENAI_NF_FISCAL_VALIDATION_FAILED',
] as const

export type DanfeFallbackFailureCode = typeof failureCodes[number]

export function safeDanfeFallbackFailureCode(value: unknown): DanfeFallbackFailureCode {
  return failureCodes.find(code => code === value) ?? 'OPENAI_NF_REQUEST_FAILED'
}
