-- Permite auditar solicitacao formal de nonce de reautenticacao do Supabase Auth.

ALTER TABLE public.seguranca_eventos
  DROP CONSTRAINT IF EXISTS seguranca_eventos_tipo_check;

ALTER TABLE public.seguranca_eventos
  ADD CONSTRAINT seguranca_eventos_tipo_check CHECK (tipo_evento IN (
    'MFA_ENROLL_INICIADO',
    'MFA_ATIVADO',
    'MFA_DESATIVADO',
    'MFA_FALHA',
    'MFA_RECOVERY_USADO',
    'MFA_RECOVERY_REGENERADO',
    'MFA_RESET_ADMINISTRATIVO',
    'SESSAO_ELEVADA',
    'SESSOES_REVOGADAS',
    'CREDENCIAL_CRIADA',
    'CREDENCIAL_TESTADA',
    'CREDENCIAL_ATIVADA',
    'CREDENCIAL_ROTACIONADA',
    'CREDENCIAL_REVOGADA',
    'CREDENCIAL_USADA',
    'ACESSO_CREDENCIAL_NEGADO',
    'ACESSO_NEGADO',
    'RATE_LIMIT_BLOQUEADO',
    'PASSWORD_RESET_REQUESTED',
    'PASSWORD_RESET_EMAIL_SENT',
    'PASSWORD_RESET_LINK_OPENED',
    'PASSWORD_RESET_LINK_INVALID',
    'PASSWORD_RESET_LINK_EXPIRED',
    'PASSWORD_RECOVERY_SESSION_CREATED',
    'PASSWORD_RECOVERY_SESSION_CLEARED',
    'PASSWORD_RESET_COMPLETED',
    'PASSWORD_RESET_ABORTED',
    'PASSWORD_CHANGED',
    'PASSWORD_CHANGE_FAILED',
    'PASSWORD_REAUTH_NONCE_REQUESTED',
    'MFA_SETUP_REQUIRED_AFTER_RESET',
    'MFA_CHALLENGE_AFTER_PASSWORD_RESET',
    'MFA_VERIFIED_AFTER_PASSWORD_RESET',
    'MFA_FAILED_AFTER_PASSWORD_RESET',
    'RECOVERY_CODE_USED',
    'MFA_REENROLL_REQUIRED',
    'AUTH_FLOW_BLOCKED_ROUTE_ATTEMPT'
  ));
